2017-03-14 11:12:00,543 ERROR: Exception on /memberlist [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 648, in memberlist
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 93, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 11:42:49,061 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 152, in template
    {% csrf_token %}
TemplateSyntaxError: Encountered unknown tag 'csrf_token'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2017-03-14 11:43:09,390 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 152, in template
    {% csrf_token %}
TemplateSyntaxError: Encountered unknown tag 'csrf_token'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2017-03-14 11:49:26,378 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 152, in template
    {% csrf-token %}
TemplateSyntaxError: Encountered unknown tag 'csrf'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2017-03-14 11:49:28,892 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 152, in template
    {% csrf-token %}
TemplateSyntaxError: Encountered unknown tag 'csrf'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2017-03-14 11:49:32,013 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 152, in template
    {% csrf-token %}
TemplateSyntaxError: Encountered unknown tag 'csrf'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2017-03-14 11:49:53,690 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 152, in template
    {% csrf-token %}
TemplateSyntaxError: Encountered unknown tag 'csrf'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2017-03-14 15:49:08,435 ERROR: Exception on /memberlist [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 665, in memberlist
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 94, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 15:52:38,913 ERROR: Exception on /admin/users [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/management/views.py", line 131, in users
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 94, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 15:52:44,627 ERROR: Exception on /admin/users [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/management/views.py", line 131, in users
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 94, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 15:52:56,295 ERROR: Exception on /admin/users [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/management/views.py", line 131, in users
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 94, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 15:57:07,245 ERROR: Exception on /memberlist [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 665, in memberlist
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 94, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 15:57:08,679 ERROR: Exception on /memberlist [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 665, in memberlist
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 94, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 15:57:09,947 ERROR: Exception on /memberlist [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 665, in memberlist
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 94, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 15:57:10,784 ERROR: Exception on /memberlist [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 665, in memberlist
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 94, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 15:57:11,980 ERROR: Exception on /memberlist [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 665, in memberlist
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 94, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-14 16:06:40,737 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 212, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 82, in _get_source_fast
    return loader.get_source(environment, template)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa3 in position 8188: invalid start byte
2017-03-14 17:06:22,081 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 212, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 3, in top-level template code
    {% set active_forum_nav=True %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name='ckCsrfToken', content="{{CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-14 17:06:22,576 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name='ckCsrfToken', content="{{CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:08:54,547 ERROR: Exception on /forum/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 149, in view_forum
    topics=topics, forumsread=forumsread,
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/forum.html", line 4, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="ckCsrfToken", content="{{ getCsrfToken() }}">
UndefinedError: 'getCsrfToken' is undefined
2017-03-15 14:08:55,067 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="ckCsrfToken", content="{{ getCsrfToken() }}">
UndefinedError: 'getCsrfToken' is undefined
2017-03-15 14:11:13,052 ERROR: Exception on /forum/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 149, in view_forum
    topics=topics, forumsread=forumsread,
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/forum.html", line 4, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:13,603 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:18,202 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 3, in top-level template code
    {% set active_forum_nav=True %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:18,643 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:19,425 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 3, in top-level template code
    {% set active_forum_nav=True %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:20,204 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:20,714 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 3, in top-level template code
    {% set active_forum_nav=True %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:21,549 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:22,091 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 3, in top-level template code
    {% set active_forum_nav=True %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:22,409 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:23,200 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 195, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 3, in top-level template code
    {% set active_forum_nav=True %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:11:23,852 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ CKEDITOR.tools.getCsrfToken() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:58:12,004 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ csrf_token() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:58:12,384 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ csrf_token() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:58:13,204 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ csrf_token() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 14:58:13,680 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ csrf_token() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 15:03:05,818 ERROR: Exception on /forum/ [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ csrf_token() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 15:03:06,208 ERROR: Exception on /favicon.ico [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/app.py", line 278, in page_not_found
    return render_template("errors/page_not_found.html"), 404
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/errors/page_not_found.html", line 3, in top-level template code
    {% extends theme("layout.html") %}
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/layout.html", line 9, in top-level template code
    <meta name="csrf-token", content="{{ csrf_token() }}">
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'CKEDITOR' is undefined
2017-03-15 16:46:34,216 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 197, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 151, in template
    {{!form.csrf_token}}
TemplateSyntaxError: unexpected char u'!' at 8190
2017-03-15 17:08:10,716 ERROR: Exception on /topic/1-welcome [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_allows/allows.py", line 98, in allower
    return f(*args, **kwargs)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 197, in view_topic
    last_seen=time_diff(), form=form)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/utils/helpers.py", line 71, in render_template
    return render_theme_template(theme, template, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 141, in render_theme_template
    return render_template(template_name, **context)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/templates/forum/topic.html", line 151, in template
    {{form = Form(csrf_enabled=False)}}
TemplateSyntaxError: expected token 'end of print statement', got '='
2017-03-16 10:03:16,806 ERROR: Exception on /ckupload/ [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2017-03-16 10:16:20,165 ERROR: Exception on /ckupload/ [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2017-03-16 10:29:00,369 ERROR: Exception on /ckupload/ [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2017-03-16 10:32:04,582 ERROR: Exception on /ckupload/ [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2017-03-16 10:37:47,280 ERROR: Exception on /ckupload/ [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2017-03-16 10:38:20,848 ERROR: Exception on /ckupload/ [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2017-03-16 10:38:35,954 ERROR: Exception on /ckupload/ [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2017-03-16 10:41:44,319 ERROR: Exception on /memberlist [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 648, in memberlist
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 93, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
2017-03-16 11:47:03,652 ERROR: Exception on /memberlist [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/views.py", line 652, in memberlist
    users = search_form.get_results().\
  File "/mnt/c/Users/nectyrael/ckflaskbb/flaskbb/forum/forms.py", line 93, in get_results
    return User.query.whooshee_search(query)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 89, in whooshee_search
    limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 150, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "/usr/local/lib/python2.7/dist-packages/flask_whooshee.py", line 167, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
